#!/bin/bash -l

# Project name
#$ -P sv-thesis

#Time limit
#$ -l h_rt=12:00:00

#Name a job
#-N defined in SampleSize.bash

#join error and output stream
#$ -j y

#Send email when job ends or aborts
#$-m e

#Name the log file
##$-o SimLog

#This line runs the set of nSim simulations this many times
#$-t 1-10

#Other options that were in script from JB
#$-l mem_per_core=8G
#$-pe omp 8
#$-l cpu_arch=!bulldozer

module load R
time Rscript SampleSizePerform.R $1
